version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      JWT_SECRET: changeme
    depends_on:
      - db
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '4200:80'

volumes:
  db-data:
